version: '3.9'
services:
  #api:
  #  container_name: api
  #  restart: always
  #  build: .
  #  ports:
  #    - '3001:${PORT}'
  #  depends_on:
  #    - db
  #  volumes:
  #    - .:/app

  db:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes: 
  postgres:
